# Generated by Django 3.2.18 on 2024-09-08 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='automations',
            name='exception',
            field=models.TextField(blank=True, null=True),
        ),
    ]
