version: "3"
services:
  db:
    container_name: db
    platform: linux/amd64 #for platform error on Apple M1 chips
    restart: always
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: db
    ports:
      - "3306:3306"