# Generated by Django 4.2.7 on 2023-12-09 18:29

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_expensecategory_paymenttype_expense_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensecategory',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='paymenttype',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=25, samples=None),
        ),
    ]
