# Generated by Django 4.2.7 on 2023-12-18 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_alter_expensecategory_color_alter_paymenttype_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensecategory',
            name='icon',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
