# Generated by Django 4.2.7 on 2023-12-18 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_expensecategory_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttype',
            name='icon',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
