# Generated by Django 4.2.7 on 2023-12-19 17:37

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_paymenttype_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', colorfield.fields.ColorField(blank=True, default='#FF0000', image_field=None, max_length=25, null=True, samples=None)),
                ('icon', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'income_categories',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('date', models.DateField()),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.incomecategory')),
                ('paymentType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.paymenttype')),
            ],
            options={
                'db_table': 'incomes',
                'ordering': ['date'],
            },
        ),
    ]
