name: one_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_side_menu: ^0.5.3
  flutter_riverpod: ^2.5.1
  shared_preferences: ^2.3.2
  dio: ^5.7.0
  intl: ^0.19.0
  easy_sidemenu: ^0.6.0
  supabase_flutter: ^2.0.0
  flutter_lints: ^4.0.0
  fl_chart: ^0.69.0
  jiffy: ^6.3.1
  material_symbols_icons: ^4.2789.0
  universal_html: ^2.2.4
  go_router: ^14.3.0
  carousel_slider: ^5.0.0
  dots_indicator: ^3.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
