name: one_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_side_menu: ^0.5.3
  flutter_riverpod: ^2.5.1
  shared_preferences: ^2.3.2
  dio: ^5.7.0
  intl: ^0.18.0
  easy_sidemenu: ^0.6.0
  supabase_flutter: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
