# Generated by Django 3.2.18 on 2024-09-15 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_habit_trackhabit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trackhabit',
            options={'ordering': ['date']},
        ),
        migrations.AddField(
            model_name='trackhabit',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
